contentColumnType: string
fieldGroup: dcb33c83-5552-4018-bede-099cfa8ac9d1 # Common
handle: cardImage
instructions: ''
name: 'Card image'
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:40166e95-77bb-4f17-96de-d077ab92e562' # Images
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: ''
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:40166e95-77bb-4f17-96de-d077ab92e562' # Images
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:40166e95-77bb-4f17-96de-d077ab92e562' # Images
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
