contentColumnType: text
fieldGroup: dcb33c83-5552-4018-bede-099cfa8ac9d1 # Common
handle: prices
instructions: ''
name: Prices
searchable: false
settings:
  addRowLabel: 'Add a row'
  columnType: text
  columns:
    __assoc__:
      -
        - col1
        -
          __assoc__:
            -
              - heading
              - 'Personal price'
            -
              - handle
              - personal
            -
              - width
              - ''
            -
              - type
              - number
      -
        - col2
        -
          __assoc__:
            -
              - heading
              - 'Small price'
            -
              - handle
              - small
            -
              - width
              - ''
            -
              - type
              - number
      -
        - col3
        -
          __assoc__:
            -
              - heading
              - 'Medium price'
            -
              - handle
              - medium
            -
              - width
              - ''
            -
              - type
              - number
      -
        - col4
        -
          __assoc__:
            -
              - heading
              - 'Large price'
            -
              - handle
              - large
            -
              - width
              - ''
            -
              - type
              - number
  defaults:
    -
      __assoc__:
        -
          - col1
          - '0.8'
        -
          - col2
          - '1.3'
        -
          - col3
          - '1.4'
        -
          - col4
          - '1.5'
  maxRows: '1'
  minRows: '1'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Table
