dateModified: 1618309395
email:
  fromEmail: pete@fantasticmachine.co.uk
  fromName: 'Craft Dev Site'
  transportType: craft\mail\transportadapters\Sendmail
plugins:
  commerce:
    edition: pro
    enabled: true
    licenseKey: Z93UF3L9ZY9186BRFDRQDV7E
    schemaVersion: 3.2.18
    settings:
      activeCartDuration: 3600
      allowEmptyCartOnCheckout: false
      autoSetNewCartAddresses: true
      cartVariable: cart
      defaultView: commerce/orders
      dimensionUnits: in
      emailSenderAddress: ''
      emailSenderAddressPlaceholder: null
      emailSenderName: ''
      emailSenderNamePlaceholder: null
      freeOrderPaymentStrategy: complete
      gatewayPostRedirectTemplate: ''
      loadCartRedirectUrl: null
      minimumTotalPriceStrategy: default
      orderPdfFilenameFormat: 'Order-{number}'
      orderPdfPath: shop/special/receipt
      orderReferenceFormat: '{{seq(7)}}'
      paymentCurrency: null
      pdfAllowRemoteImages: false
      pdfPaperOrientation: portrait
      pdfPaperSize: letter
      purgeInactiveCarts: true
      purgeInactiveCartsDuration: 7776000
      requireBillingAddressAtCheckout: false
      requireShippingAddressAtCheckout: false
      requireShippingMethodSelectionAtCheckout: false
      showCustomerInfoTab: true
      updateBillingDetailsUrl: ''
      updateCartSearchIndexes: true
      useBillingAddressForTax: false
      validateBusinessTaxIdAsVatId: false
      validateCartCustomFieldsOnSubmission: false
      weightUnits: g
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
system:
  edition: pro
  live: true
  name: 'Craft Dev Site'
  schemaVersion: 3.6.7
  timeZone: America/Los_Angeles
